INPUT = "/content/intro.mp3"  # Your input video/audio file
WHISPER_MODEL = "base"
DIMENSION = "1920x1080"
MUSIC_DIR = "Music"
FONT = "Helvetica-Bold"
FONT_SIZE = 50
TEXT_COLOR = "#ffffff"
STROKE_COLOR = "#ff3d00"
STROKE_WIDTH = 2
SUBTITLE_STYLE = "word"  # Options: "word", "word-background", "off"
HIGHLIGHT_COLOR = "#ff3d00"
MAX_CHARACTERS_PER_LINE = 15
MAXIMUM_LINES_PER_PAGE = 2
X_POSITION = 25
Y_POSITION = 125
PEXELS_API_KEY = "YOUR_API_KEY"  # Replace with your Pexels API key
